/* this is perhtm.h */

char my_aspect_text[512];

struct aspect {
  char *asp_code;
  char *asp_text;
} p_asptab[] = {
  {"p01101", "You have plenty of energy and like to take the initiative in all actions.  Your courage in the face of obstacles can be used to help others."},
  {"p01102", "Although you are down to earth you have great determination. Your loyalty makes you an excellent friend."},
  {"p01103", "You have great mental energy and can handle fast-changing situations easily because of your versatility."},
  {"p01104", "Your sensitivity to those in need brings a lot of comfort to those around you- especially in the family."},
  {"p01105", "Your natural power and authority helps you in the role of leadership and guidance for those in need."},
  {"p01106", "Your quiet practical nature lets you analyze situations and lets you create a high standard of excellence in many areas."},
  {"p01107", "Your intuitive sense for relationships of all kinds helps you create an atmosphere of peace and harmony."},
  {"p01108", "Your intense drive and creative power can quickly turn a negative situation into an amazingly better one."},
  {"p01109", "Your vast desire to expand your horizons both physically and mentally can help you be an ideal of honor and freedom."},
  {"p01110", "Your constructive energy helps you drive steadily forward to a successful life of dedication to a goal."},
  {"p01111", "You have independent and uncompromising dedication to ideals of love and brotherhood in groups and in society."},
  {"p01112", "Deep sympathy and sensitivity to the feelings of others make you a great source of compassion and comfort."},
  {"p01201", "You have a sunny disposition and great vitality."},
  {"p01202", "You have a strong desire to achieve financial independence."},
  {"p01203", "You are in contact with bright and witty people and you love to experience new things."},
  {"p01204", "It's important to you to establish a stable home and family.  You could do well in real estate."},
  {"p01205", "You have much vitality which could be expressed in sports, show business or artistic pursuits.  You are popular, love children and are a passionate lover.  This favorable indication is said to have to do with creation, recreation and procreation."},
  {"p01206", "You can succeed in an area involving giving service to others such as doctor, nurse, veterinarian or nutritionist."},
  {"p01207", "Marriage or other partnerships can be of the utmost importance to you in your life.  You can be a good at selling or in public relations."},
  {"p01208", "You could be good at a business like accounting, taxes, insurance or some other business which deals with other people's money."},
  {"p01209", "You can have an interest in travel, spiritual things, philosophy or publishing."},
  {"p01210", "You have a strong will to succeed and by hard work you can achieve a position of responsibility, wealth or power."},
  {"p01211", "You can attract many friends and you enjoy working in groups of people."},
  {"p01212", "You have a strong inner life and could do well helping others in institutions."},
  {"p01b02", "There likely was a basic inharmony in the home you grew up in."},
  {"p01b05", "You are a risk-taker because of impulsive behavior and temper flare-ups."},
  {"p01b06", "You tend to be over-optimistic and unrealistic.  You see a grand overall plan but can be defeated by being unable to handle details."},
  {"p01b07", "You will be subject to frequent delays and frustrations, but you can succeed through very hard work.  There can be some difficulty in dealing with laws and rules of all kinds."},
  {"p01b08", "Your efforts to be individualistic at all costs can lead to erratic behavior or perverse wrong-headedness.  You are very changeable."},
  {"p01b09", "An impractical fogginess can lead you to deceive or be deceived.  You could tend to escape hardships in an unhealthy way."},
  {"p01b10", "Your domineering and aggressive nature can cause difficulties."},
  {"p01c02", "With the sun and moon very close together in your horoscope good or bad times will be greatly magnified in your life."},
  {"p01c03", "The way your mind works to attack problems is in accord with the personality traits of your sun sign."},
  {"p01c04", "You are cheerful and affectionate and could have talent in music or art.  You are good with children."},
  {"p01c05", "You have strong willpower and your self-assertion helps you in sports or in leadership."},
  {"p01c06", "You are optimistic, outgoing and generous and could do well in religion, law or philosophy."},
  {"p01c07", "Your nature is serious and you can achieve success by solid organization, attention to duty and good, hard work."},
  {"p01c08", "You have unusual interests and you dislike conventions.  You could do well in science, the media, reform of all kinds or the occult."},
  {"p01c09", "Your very active imagination could be used for art, music or mysticism.  Without strong mental control poor judgement could result."},
  {"p01c10", "You have incredible willpower.  You can be good at going into a failing situation and turning it into a success."},
  {"p01g02", "There is a basic harmony in your personality because the sun and moon form a good aspect."},
  {"p01g05", "You have strong willpower and your self-assertion helps you in sports or in leadership."},
  {"p01g06", "You are optimistic, outgoing and generous and could do well in religion, law or philosophy."},
  {"p01g07", "Your nature is serious and you can achieve success by solid organization, attention to duty and good, hard work."},
  {"p01g08", "You have unusual interests and you dislike conventions.  You could do well in science, the media, reform of all kinds or the occult."},
  {"p01g09", "Your very active imagination could be used for art, music or mysticism.  Without strong mental control poor judgement could result."},
  {"p01g10", "You have incredible willpower.  You can be good at going into a failing situation and turning it into a success."},
  {"p02101", "You hide a bar of steel inside.  You can have impulsive moods with short flare-ups of temper- especially in the home."},
  {"p02102", "Your emotions are steady and controlled.  You have a \"green thumb\".  You can overvalue luxuries and material comforts but have good luck with money."},
  {"p02103", "Your moods are extremely changeable and you are restless and can often change your place of residence."},
  {"p02104", "You have extreme depth to your emotions which ideally shows itself in a loving home environment.  The stomach is a sensitive area."},
  {"p02105", "You can get security through dramatic behavior.  You enjoy dominating the home life."},
  {"p02106", "You are shy and tend to analyze your emotions.  Your concern for good nutrition can help you in cooking."},
  {"p02107", "You have sensitivity to the reactions of others.  This can eventually lead to an excellent marriage.  You can have skill in public relations and advertising."},
  {"p02108", "Your emotions run deep with an all-or-nothing intensity. Your suspicious nature and non-stop research make you a natural detective."},
  {"p02109", "Your moods are expansive as is your mind.  You can live in foreign countries or in many homes."},
  {"p02110", "You are down to earth, take your responsibilities seriously and are much aware of other's approval.  You're likely to be before the public."},
  {"p02111", "You like to keep your independence from others by controlling your emotions.  You demand a lot of freedom in your home life."},
  {"p02112", "You are super-emotional and can easily brood or change your mood.  You find security in secluded places by yourself. Your sensitivity can lead you to avoid facing hard realities."},
  {"p02201", "You can be changeable and moody."},
  {"p02202", "Money matters form a large part of your life.  You could earn money through dealings with the public."},
  {"p02203", "You have a restless curiosity and you're constantly moving around."},
  {"p02204", "You have a strong emotional tie to the home and family. Your business could deal with home products."},
  {"p02205", "You could do well dealing with babies and children.  Your activities could bring you before the public."},
  {"p02206", "You could change your type of work often.  Food could play a large role in your work."},
  {"p02207", "There could be a changeableness concerning your marriage partner.  You are very likely to have dealings with the public."},
  {"p02208", "You have intense emotions and could have some interest in the psychic or occult fields.  Your work could involve dealing with women."},
  {"p02209", "Home might well be in a foreign land at some time in your life."},
  {"p02210", "You may change your career several times.  You are likely to be prominently before the public."},
  {"p02211", "You have many friends who change constantly.  A large part of your life could be meeting with them."},
  {"p02212", "You have emotional sensitivity and can easily withdraw into inaction."},
  {"p02b03", "You have a nervous disposition and you love to talk a mile a minute.  You should avoid endless chit-chat or gossip."},
  {"p02b04", "You could be too trusting of people who take advantage of you."},
  {"p02b05", "Your emotions have a combative side to them, especially in the home."},
  {"p02b06", "You can be overly emotional and this, of course, can lead to overeating."},
  {"p02b07", "Your moods can often be negative and great effort is needed to snap out of it.  You don't care for authority and you can have a loose attitude toward rules."},
  {"p02b08", "You can have sudden big changes in mood.  You can have very high ability but then you can ruin a project with sudden inappropriate actions."},
  {"p02b09", "You are subject to emotional confusion which sometimes leads to a tendency to unhealthy means of escape such as dependencies."},
  {"p02b10", "You can be dominating in relationships- especially in the home."},
  {"p02c03", "You have fine mental abilities along with common sense."},
  {"p02c04", "You have a pleasant disposition and appreciation of fine things.  This is a good indicator of luck in love.  You could have a pleasant voice or be a singer."},
  {"p02c05", "You have strong emotions with an occasional angry outburst."},
  {"p02c06", "You have generosity and a caring attitude, especially toward children.  You are lucky in money."},
  {"p02c07", "Your emotions are very well controlled and your common sense is good in business- especially real estate."},
  {"p02c08", "You have very erratic moods but good intuition and clever originality in problem solving."},
  {"p02c09", "You are very highly attuned to your emotions and those of others.  You could be psychic or artistic."},
  {"p02c10", "You have very strong-willed emotions."},
  {"p02g03", "You have fine mental abilities along with common sense."},
  {"p02g04", "You have a pleasant disposition and appreciation of fine things.  This is a good indicator of luck in love.  You could have a pleasant voice or be a singer."},
  {"p02g05", "You have strong emotions with an occasional angry outburst."},
  {"p02g06", "You have generosity and a caring attitude, especially toward children.  You are lucky in money."},
  {"p02g07", "Your emotions are very well controlled and your common sense is good in business- especially real estate."},
  {"p02g08", "You have very erratic moods but good intuition and clever originality in problem solving."},
  {"p02g09", "You are very highly attuned to your emotions and those of others.  You could be psychic or artistic."},
  {"p02g10", "You have very strong-willed emotions."},
  {"p03101", "You are quick witted but need more patience to keep your mind on one job long enough to do anything completely and successfully."},
  {"p03102", "You have good concentration and can do well in the mental arts of music and writing. Your throat is a sensitive area."},
  {"p03103", "You can get lots of work done because you're so versatile. Being a great talker and communicator can make you a good teacher.  You need to concentrate your forces more and stop to think before speaking."},
  {"p03104", "Emotional factors fog your thinking, but the feeling associated with ideas gives you a good memory.  Your skill at spotting the value of things helps you in business."},
  {"p03105", "Your self-confidence can give you strong concentration.  You are good at giving orders but remember that others are whole persons in their own right."},
  {"p03106", "You have an analytical mind of great ability.  You are precise and good at working with fine details in areas like writing, medicine and mathematics. You see things clearly so beware of fault-finding.  The lungs are a sensitive area."},
  {"p03107", "Your mind runs naturally to study relationships.  Your mental control over emotion can make you good at law, psychology or public relations and advertising."},
  {"p03108", "Your intensity makes you good at digging up information and getting to the truth of the matter."},
  {"p03109", "You love to roam.  You enjoy travel and have a flair for languages.  You are honest and direct in speech but you must try to control your criticism."},
  {"p03110", "You have a serious attitude and like to strive for goals.  You are practical and organized which makes you good at business."},
  {"p03111", "You have great original ideas but need someone to put them into action.  You are an independent thinker and are naturally drawn to unusual subjects like astrology, science fiction and psychic phenomena."},
  {"p03112", "You are imaginative and intuitive.  Your emotions can be played upon.  Your thinking needs to be more detached and impersonal."},
  {"p03201", "You have an intellectual outlook on life and have a desire to express yourself in speech and writing."},
  {"p03202", "You could earn money in communications or through a fast-changing job like travelling salesman."},
  {"p03203", "You are a natural writer, speaker or teacher."},
  {"p03204", "You could have an interest in real estate or ecology."},
  {"p03205", "You have an intellectual outlook on creativity.  You could be a critic or writer in this area."},
  {"p03206", "You take a sense of duty and efficient approach to your work.  You could do well in medicine or science.  Avoid overwork."},
  {"p03207", "You are good at bargaining and negotiations, the law, public relations, or psychology."},
  {"p03208", "You are good at digging into facts like a detective and figuring out the solution in a situation involving intrigue or crime."},
  {"p03209", "Your interests range widely and you could enjoy writing or travelling."},
  {"p03210", "Your speaking or writing ability could bring you before the public.  You are good at finding clever ways to do things in business."},
  {"p03211", "You are very interested in new and unusual ideas and you could invent clever things or new, better ways to do things."},
  {"p03212", "You can have a tendency to let emotional factors affect your decisions."},
  {"p03b05", "If your mental combativeness is not controlled, abusiveness, a sharp tongue, and irritability may result."},
  {"p03b06", "Over-optimism and lack of attention to details can lead to failures.  Your intentions are good, but biting off more than you can chew doesn't help anyone."},
  {"p03b07", "You tend to worry and be pessimistic about things. You can sometimes plot and scheme when simple straightforwardness would be more successful."},
  {"p03b08", "You are both stubborn and very outspoken and you have no trouble at all with low self-esteem.  You can make decisions which are too sudden and too drastic and then push these ideas very hard even in the face of great evidence that you're wrong."},
  {"p03b09", "Day-dreaming and foggy thinking can be a hindrance for you.  You can easily deceive or be deceived."},
  {"p03b10", "You are blunt in your speech and are good at being sneaky."},
  {"p03c04", "You are generally happy and cheerful. You communicate with grace and harmony and could be good at some kind of writing or other creative activity."},
  {"p03c05", "Your thinking can be incisive and vigorous.  You like debate and aren't afraid to say what you think."},
  {"p03c06", "You are good-natured and kind and could be involved with religion, law or literature."},
  {"p03c07", "You tend to be patient and serious in your thinking and you can be good at detailed, logical work like mathematician, scientist or craftsman."},
  {"p03c08", "You are extremely independent and you can have clever, highly original ideas.  You could do well in science- especially electronics in any form.  You like to study things at the leading edge like computers, science fiction, astrology or psychic phenomena."},
  {"p03c09", "You have a vivid imagination and you could be interested in mysticism, psychic phenomena, poetry, musical composition or magic."},
  {"p03c10", "You are very resourceful and are good at digging out information from unlikely places."},
  {"p03g04", "You are generally happy and cheerful. You communicate with grace and harmony and could be good at some kind of writing or other creative activity."},
  {"p03g05", "Your thinking can be incisive and vigorous.  You like debate and aren't afraid to say what you think."},
  {"p03g06", "You are good-natured and kind and could be involved with religion, law or literature."},
  {"p03g07", "You tend to be patient and serious in your thinking and you can be good at detailed, logical work like mathematician, scientist or craftsman."},
  {"p03g08", "You are extremely independent and you can have clever, highly original ideas.  You could do well in science- especially electronics in any form.  You like to study things at the leading edge like computers, science fiction, astrology or psychic phenomena."},
  {"p03g09", "You have a vivid imagination and you could be interested in mysticism, psychic phenomena, poetry, musical composition or magic."},
  {"p03g10", "You are very resourceful and are good at digging out information from unlikely places."},
  {"p04101", "If you're artistic you're good at the clean lines of interior decoration, graphic art or fashion design.  In love you are aggressive in your affections and maybe even self-centred.  You could rush into relationships, forgetting that love takes time to flower.  You can have a positive, cheerful attitude in love."},
  {"p04102", "You have a strong and constant love nature and stability in love is important to you.  The sense of touch can be important in your creative efforts, as in painting, sculpture, weaving or gardening.  Your love of luxury could lead to overindulgence in the wine, women and song and the lazy life of the self-indulgent.  In love you are at the top in loyalty and the real depth of your feelings."},
  {"p04103", "You are very attractive because of your light-hearted charm.  You are an excellent talker and good at jokes.  You like variety in love and can be involved with more than one relationship at a time.  You need to strive for greater maturity and decide what you want in the love area."},
  {"p04104", "You are very sensitive in relationships and are prone to fall very deeply in love.  The best expression of your very warm love is in the home environment.  When things go wrong you can have uncontrolled emotionalism."},
  {"p04105", "You are a lover of life and have a dramatic expression of love.  You could be an actor or other performer.  You are an outgoing and sunny romantic.  You are fond of children."},
  {"p04106", "You have an analytical approach to love and can be too critical of the one you love.  Marriage can late because of your high standards in a mate.  Your desire to serve others makes you a good doctor, nurse or other helping professional.  In art you can be good in the mental arts like design, writing or music."},
  {"p04107", "Harmonious relationships are of the utmost importance to you.  Your natural understanding of other's feelings and your refinement can make you good at fashion, beauty, interior decoration or design.  You are good at resolving conflicts.  You should not hold back your feelings for fear of breaking the harmony."},
  {"p04108", "You have a passionate love nature and can love one person through everything.  Your intense feelings can lead to jealousy and to difficulty in getting over hurts from loved ones."},
  {"p04109", "You can be friendly, sociable and charming and enjoy having numerous relationships.  You love travel and probably will have a relationship with someone who ends up some distance away."},
  {"p04110", "In love you are faithful and generous but not very outgoing in expression.  You find it difficult to show more affection.  You may marry later on or have an older partner."},
  {"p04111", "You do well being friendly with everyone but find it harder to form a deep relationship with one person.  Love for you can often be sudden and superficial.  You demand freedom in your relationships."},
  {"p04112", "In love you have excessive emotionalism which can cause you to see the partner through rose-colored glasses.  More control and a steadier expression of love can avoid heartaches.  You can be very creative in almost any area of the arts, especially the rhythm arts- music, dance and poetry."},
  {"p04201", "You have an aspect which makes you good-looking, friendly and gives you the ability to mix in social situations."},
  {"p04202", "You could earn money through luxury items or through your relationships.  You love the fine things that a lot of money can buy."},
  {"p04203", "You have a nice voice and appreciate beautiful writing."},
  {"p04204", "You like your home to be very artistically decorated."},
  {"p04205", "You can have a romantic nature.  You can be creative and successful in the arts.  You could do well working with children."},
  {"p04206", "Your work could involve luxury items, clothing, art or services for women."},
  {"p04207", "You have potential for a happy marriage and social popularity."},
  {"p04208", "You could gain financially through a loved one.  You have a passionate nature."},
  {"p04209", "You love to take frequent vacation trips especially to foreign countries."},
  {"p04210", "You have ambition in the arts or in climbing up the social ladder."},
  {"p04211", "You have many friends because of your warmth and kindness.  You can attract friends in the arts or entertainment."},
  {"p04212", "In love you are shy and secretive but very emotional.  You are likely to move in artistic circles."},
  {"p04b05", "You are very passionate but abrupt actions or an overly emotional attitude may cause difficulties."},
  {"p04b06", "You love luxuries and fine things but may tend toward idleness, self-indulgence and the enjoyment of social status.  You have a great capacity to give love."},
  {"p04b07", "Difficult love relationships in the past create a block in the flow of love energies.  You could have a relationship with someone of considerable difference in age, in wealth or in social status."},
  {"p04b08", "In love you can have sudden or unstable relationships.  You have a great need for freedom and independence and you can have unusual partners, all of which make for love problems."},
  {"p04b09", "You can be \"fooled by love\".  You need to try and see the other person clearly with your feet solidly on the ground.  It's only too easy to float into the clouds of love and see your partner only through rose-colored glasses."},
  {"p04b10", "In love you can have intense and passionate involvements.  You can gain financially through relationships."},
  {"p04c05", "You can be warm and affectionate and in love you are passionate.  You have the drive to develop any creative abilities you may have."},
  {"p04c06", "You have an optimistic and happy disposition and could do well in music (especially singing) or the arts."},
  {"p04c07", "In love you have some underlying duty or obstacle resulting in an emotional restriction.  You could do well in music."},
  {"p04c08", "In love you are prone to have sudden attractions and exciting adventures.  You could have sudden good luck in money."},
  {"p04c09", "You are highly creative and could do extremely well in a wide range of creative activities.  Your extreme sensitivity helps you in this but, of course, it also leads to much sorrow at times."},
  {"p04c10", "You are very passionate in love."},
  {"p04g05", "You can be warm and affectionate and in love you are passionate.  You have the drive to develop any creative abilities you may have."},
  {"p04g06", "You have an optimistic and happy disposition and could do well in music (especially singing) or the arts."},
  {"p04g07", "In love you value loyalty very highly.  A sense of order and control helps any creative potential you may have."},
  {"p04g08", "In love you are prone to have sudden attractions and exciting adventures.  You could have sudden good luck in money."},
  {"p04g09", "You are highly creative and could do extremely well in a wide range of creative activities.  Your extreme sensitivity helps you in this but, of course, it also leads to much sorrow at times."},
  {"p04g10", "You are very passionate in love.  Money could drop into your lap from partners or inheritance."},
  {"p05101", "Your have an incredible amount of energy which is well released in sports.  Your courage, initiative and big ego make you a natural leader.  Without control your energy can be dangerous, especially for head injuries.  You could work well with machinery or tools."},
  {"p05102", "Your energy is backed by determination giving you physical stamina.  Your hard work can give you success but there's no sense trying to put your head through a brick wall."},
  {"p05103", "You can be good with your hands as in surgery or in co-ordination sports like table tennis or mentally in mechanics or engineering.  Mental competition as in chess or debate or journalism could interest you.  Control is needed to avoid verbal abuse and irritability.  The hands are a sensitive area."},
  {"p05104", "You have a lot of emotional energy which, if uncontrolled, can lead to strife- especially in the home.  The stomach is a sensitive area."},
  {"p05105", "Lots of physical strength and endurance make you a leader who loves a challenge.  If you can avoid a chip on your shoulder there can be success in sports or the military."},
  {"p05106", "Your energy is directed in a careful, intelligent way, making you a skilled craftsman.  Avoid wasting time on non-essential projects.  You could do well at tennis or chess."},
  {"p05107", "You have a drive to correct injustice which can lead to success but can cause you to create strife in your partnerships."},
  {"p05108", "Your energy has incredible power which you can use to fight for the underdog.  You will fight to the end for what you think is right.  Your all-or-nothing attitude can lead to intense jealousy.  You make a great friend or a terrible enemy.  You could be a good detective."},
  {"p05109", "Your actions are direct and open.  You can spend a lot of energy in travelling and in supporting your convictions, even before the courts.  Your love of adventure can attract you to the freedom sports- skiing, horses, sailing, soaring and race driving."},
  {"p05110", "Your energy is very effectively used in your role in life.  You have excellent control of your energies which will help you achieve success.  Your one-pointed drive to achievement should not lead to ruthlessness or to the sacrificing of your emotional life."},
  {"p05111", "You can work well in team work or in a scientific setting or in political reform.  Your energy can be expressed in a haphazard way or in unusual courses of action."},
  {"p05112", "Decisive action can be hindered by your inappropriate emotional concerns.  You could be a good dancer or skater.  The feet are a sensitive area."},
  {"p05201", "You are aggressive and strong and love to express yourself physically as in sports."},
  {"p05202", "You may spend money too impulsively and have a tremendous drive to earn money."},
  {"p05203", "You are impatient and quick thinking but you drive too fast."},
  {"p05204", "Avoid creating strife in the home."},
  {"p05205", "You can be passionate in romance and in competition.  You could make a good coach."},
  {"p05206", "You could well in work involving tools- craftsman, engineer, tradesman, surgeon."},
  {"p05207", "You have tendency to enter partnerships rather too quickly, and to try to dominate them once you're in."},
  {"p05208", "You are extremely persistent- especially about money and are likely to get into disputes about money."},
  {"p05209", "You have strong convictions about philosophy or politics.  You could enjoy outdoor sports like horseback riding, skiing or sailing."},
  {"p05210", "Your want to make a name for yourself and you have the controlled drive to do it.  This indicator is often found in surgeons and other competent and successful people."},
  {"p05211", "You could be around people with mechanical or electrical ability.  You have strong ideas for social reform."},
  {"p05212", "Your actions can tend to be secretive.  In institutions you can be a \"disturber\" who bucks authority."},
  {"p05b06", "Over-enthusiasm can lead to extravagance or gambling.  Beware of biting off more than you can chew."},
  {"p05b07", "Your actions are frequently frustrated.  This can lead to very uneven effort in a project- working hard for awhile but then doing nothing.  You are switching from an overly repressive to an overly energetic state."},
  {"p05b08", "You can have explosive flare-ups of temper.  Patience and humility are needed, for you tend to want your own way at all costs.  Dangerous thrill-seeking can be a problem."},
  {"p05b09", "While sometimes your actions are uncertain, you have a magnetism which gives you natural ability as a leader."},
  {"p05b10", "You are very forceful and must work hard to avoid violence.  Boxing, karate or judo are good sports for you."},
  {"p05c06", "You have an abundance of enthusiasm so when you start out on a project there's no stopping you."},
  {"p05c07", "Your energy output can vary greatly as though you were driving with the breaks on.  This could make you accident-prone."},
  {"p05c08", "Your actions can be impulsive and erratic.  You love excitement and seek it out in things like car racing."},
  {"p05c09", "You have strong personal magnetism.  Your energy can be used in a harmonious way as in yoga or dancing."},
  {"p05c10", "You have tremendous energy and a dynamic attitude toward life."},
  {"p05g06", "You have an abundance of enthusiasm so when you start out on a project there's no stopping you."},
  {"p05g07", "You have both great energy and the control of it- elements which ensure success.  You have willpower but it's well-balanced.  You are ambitious and have every chance of advancement to a position of authority."},
  {"p05g08", "You can be very ingenious in mechanical or electrical skills. You love action and are able to make quick decisions in stressful conditions."},
  {"p05g09", "You have strong personal magnetism.  Your energy can be used in a harmonious way as in yoga or dancing."},
  {"p05g10", "You have tremendous energy and a dynamic attitude toward life."} 
};

#define NKEYS_ASP (sizeof p_asptab / sizeof(struct aspect))


/* end of perhtm.h */
